### ISSUE TITLE
Cronjob does not get installed while installing the plugin

### ISSUE THREAD

**Issue by pt1602** [StephanAltmann85/shopware5-ecb-currency-rates#1]
Hello, 

I recently started using your plugin. Everything works fine so far but as it seems the cronjob does not get installed.

I tried adding it manually but could not find a proper documentation for that. So can you give me some informations? 

Shopware Version: 5.6.7 (Cron Plugin is installed)

**Comment by StephanAltmann85** [comment]
Hmm,

have you checked the table „s_crontab“? Does the Cronjob exist inside this table?
